In [20]:
l=[]
for i in range(2000,3201):
  if (i%7==0 and i%5!=0):
    l.append(i)
print(l)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [6]:
n=int(input("enter a positif number"))
while(n<0):
  n=int(input("enter a positif number"))
factorial=1
while(n>0):
  factorial*=n
  n-=1
print(factorial)

enter a positif number65
8247650592082470666723170306785496252186258551345437492922123134388955774976000000000000000


In [9]:
n=int(input("enter a positif number"))
while(n<0):
  n=int(input("enter a positif number"))
d={}
for i in range (1,n+1):
  d[i]=i*i
print(d)

enter a positif number8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [15]:
ch=input("enter a sting ")
n=int(input("enter a positif number in the range of the string length "))
while(n<0 or n>len(ch)-1):
  n=int(input("enter a positif number in the range of the string length "))
ch=ch[0:n]+ch[n+1:]
print(ch)

enter a sting abcdefgh
enter a positif number in the range of the string length 4
abcdfgh


In [74]:
import numpy as np
tab=np.random.randn(3,4)
print(tab)
l=[]
print(tab.shape[0])
for i in range (tab.shape[0]):
  l.append(tab[i].tolist())
print(l)

[[-0.1178367   1.54138006  3.87514688  0.42885737]
 [ 0.49429758 -0.96451907  0.26532383  1.43007892]
 [-0.50061645  1.67813049 -0.40956333  1.01526099]]
3
[[-0.11783670396946089, 1.5413800565808222, 3.875146876027744, 0.42885736628314636], [0.494297578798965, -0.9645190727868953, 0.26532383270198445, 1.4300789209393239], [-0.5006164460295985, 1.6781304854286736, -0.4095633290450607, 1.0152609932454206]]


In [32]:
import numpy as np
tab1=np.random.randn(3)
tab2=np.random.randn(3)
arr=np.cov(tab1,tab2)
print(arr)

[[1.39775943 1.55842493]
 [1.55842493 3.32028131]]


In [42]:
import math
ch=input("enter the values for D separated by a comma")
l=ch.split(",")
q=[]
h=30
c=50
print(len(l))
for i in range(len(l)):
  q.append(int(math.sqrt((2*c*int(l[i]))/h)))
print(q)


enter the values for D separated by a comma100,150,180
3
[18, 22, 24]
